package com.techullurgy.howzapp.feature.chat.database.utils

internal const val DISCRIMINATOR_COLUMN = "type"

internal object MessageConstants {
    const val DISCRIMINATOR_TEXT_MESSAGE = "TEXT_MESSAGE"
    const val DISCRIMINATOR_IMAGE_MESSAGE = "IMAGE_MESSAGE"
    const val DISCRIMINATOR_VIDEO_MESSAGE = "VIDEO_MESSAGE"
    const val DISCRIMINATOR_AUDIO_MESSAGE = "AUDIO_MESSAGE"
    const val DISCRIMINATOR_DOCUMENT_MESSAGE = "DOCUMENT_MESSAGE"

    const val DISCRIMINATOR_NON_UPLOADABLE_PENDING_MESSAGE = "NON_UPLOADABLE_PENDING_MESSAGE"
    const val DISCRIMINATOR_UPLOADABLE_PENDING_MESSAGE = "UPLOADABLE_PENDING_MESSAGE"
}

internal object ChatTypeConstants {
    const val DISCRIMINATOR_DIRECT_CHAT = "DIRECT_CHAT"
    const val DISCRIMINATOR_GROUP_CHAT = "GROUP_CHAT"
}

internal object OnlineStatusConstants {
    const val DISCRIMINATOR_NO_ONLINE_STATUS = "NO_ONLINE_STATUS"
    const val DISCRIMINATOR_ONLINE = "ONLINE"
    const val DISCRIMINATOR_OFFLINE = "OFFLINE"
}

internal object UploadStatusConstants {
    const val DISCRIMINATOR_UPLOAD_SUCCESS = "UPLOAD_SUCCESS"
    const val DISCRIMINATOR_UPLOAD_PROGRESS = "UPLOAD_PROGRESS"
    const val DISCRIMINATOR_UPLOAD_CANCELLED = "UPLOAD_CANCELLED"
    const val DISCRIMINATOR_UPLOAD_FAILED = "UPLOAD_FAILED"
    const val DISCRIMINATOR_UPLOAD_STARTED = "UPLOAD_STARTED"
    const val DISCRIMINATOR_UPLOAD_TRIGGERED = "UPLOAD_TRIGGERED"
}